# Generated by Django 2.1.3 on 2018-11-15 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rtitle', models.CharField(max_length=100)),
                ('Rinstitution', models.CharField(max_length=100)),
                ('Rintroduction', models.TextField()),
                ('Rpublish', models.DateTimeField(auto_now_add=True)),
                ('Rcategory', models.CharField(max_length=100)),
                ('Rfund', models.IntegerField(default=0)),
                ('Rrank', models.CharField(max_length=100)),
                ('Rjournal', models.CharField(max_length=100)),
                ('Rauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Rpublish',),
            },
        ),
    ]
